apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lego
spec:
  schedule: "0 1 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lego
            image: repository

            args:
            - /bin/sh
            - /aliyun/start.sh

            envFrom:
            - configMapRef: 
                name: lego.env

          imagePullSecrets:
          - name: coding.devos

          restartPolicy: Never
